language: c

addons:
    apt:
        packages:
            - elfutils
            - zlib1g-dev
            - mingw32
            - mingw32-binutils
            - cmake
os:
    - linux
    - osx

compiler:
    - clang
    - gcc

matrix:
    include:
        - os: linux
          compiler: i586-mingw32msvc-gcc
          env: HOST="--host=i586-mingw32msvc" TEST="test/main.exe"
        - os: linux
          compiler: clang
          env: CFLAGS="-fsanitize=address -g" ASAN_OPTIONS="detect_leaks=0"

    exclude:
        - os: osx
          compiler: gcc

script:
    - cmake -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - ctest -V